#Requires AutoHotkey v2.0
; This file is partially generated from karabiner/karabiner.json.
; Add custom hotkeys outside the managed block.

; Mac-like modifier positions on a typical Windows keyboard:
; - Left Alt behaves like Left Control
; - Left Win/Copilot behaves like Left Alt
; - Left Fn (assumed SC163) behaves like Left Win/Copilot
; - Left Control behaves like Left Fn (assumed SC163)
LAlt::LControl
LWin::LAlt
SC163::LWin
LControl::SC163

; BEGIN AUTO-GENERATED FROM KARABINER
; DO NOT EDIT INSIDE THIS BLOCK
; Run: npm run win:sync-hotkeys
; Source: karabiner/karabiner.json (selected profile, enabled rules only)
; Unsupported mappings are skipped and counted in script output
; Generated by ahk/karabiner-to-ahk.ts at 2026-02-27T14:02:44.499Z
^!+h::Send("{Left}")
^!+j::Send("{Down}")
^!+k::Send("{Up}")
^!+l::Send("{Right}")
; END AUTO-GENERATED FROM KARABINER
