#Requires AutoHotkey v2.0
; This file is partially generated from karabiner/karabiner.json.
; Add custom hotkeys outside the managed block.

; BEGIN AUTO-GENERATED FROM KARABINER
; DO NOT EDIT INSIDE THIS BLOCK
; Run: npm run win:sync-hotkeys
; Source: karabiner/karabiner.json (selected profile, enabled rules only)
; Unsupported mappings are skipped and counted in script output
; Generated by ahk/karabiner-to-ahk.ts at 2026-02-27T13:52:05.167Z
^!+h::Send("{Left}")
^!+j::Send("{Down}")
^!+k::Send("{Up}")
^!+l::Send("{Right}")
; END AUTO-GENERATED FROM KARABINER
