#Requires AutoHotkey v2.0
; This file is partially generated from karabiner/karabiner.json.
; Add custom hotkeys outside the managed block.

; BEGIN AUTO-GENERATED FROM KARABINER
; DO NOT EDIT INSIDE THIS BLOCK
; Run: npm run win:sync-hotkeys
; Source: karabiner/karabiner.json (selected profile, enabled rules only)
; Unsupported mappings are skipped and counted in script output
; Generated by ahk/karabiner-to-ahk.ts
*CapsLock::
{
	Send("{Blind}{LAlt DownR}{LShift DownR}{LControl DownR}")
	KeyWait("CapsLock")
	Send("{Blind}{LControl Up}{LShift Up}{LAlt Up}")
	if (A_PriorKey = "CapsLock") {
		Send("{Escape}")
	}
}
*LAlt::
{
	Send("{Blind}{LAlt DownR}{LShift DownR}{LControl DownR}")
	KeyWait("LAlt")
	Send("{Blind}{LControl Up}{LShift Up}{LAlt Up}")
	if (A_PriorKey = "LAlt") {
		Send("{LAlt}")
	}
}
^!+h::Send("{Left}")
^!+j::Send("{Down}")
^!+k::Send("{Up}")
^!+l::Send("{Right}")
; END AUTO-GENERATED FROM KARABINER
