import { PATHS } from "../paths"
import type { CreateInstallModule, TerminalAnsi, ThemeTokens, Variant } from "../types"
import { deriveTerminalAnsi, installFile, writeText } from "../utils"

const ANSI_ORDER: Array<keyof TerminalAnsi> = [
  "black",
  "red",
  "green",
  "yellow",
  "blue",
  "magenta",
  "cyan",
  "white",
  "brightBlack",
  "brightRed",
  "brightGreen",
  "brightYellow",
  "brightBlue",
  "brightMagenta",
  "brightCyan",
  "brightWhite",
]

function buildGhosttyTheme(variant: Variant): string {
  const terminalAnsi = deriveTerminalAnsi(variant)
  const lines = [
    "# Generated by custom-themes/create/apps/ghostty.ts",
    `background = ${variant.background}`,
    `foreground = ${variant.foreground}`,
    `cursor-color = ${variant.cursor}`,
    `selection-background = ${variant.selectionBackground}`,
    `selection-foreground = ${variant.selectionForeground}`,
  ]

  ANSI_ORDER.forEach((name, index) => {
    lines.push(`palette = ${index}=${terminalAnsi[name]}`)
  })

  return `${lines.join("\n")}\n`
}

export const ghosttyApp: CreateInstallModule = {
  appName: "ghostty",
  async create(tokens: ThemeTokens) {
    await writeText(PATHS.output.ghostty.dark, buildGhosttyTheme(tokens.variants.dark))
    await writeText(PATHS.output.ghostty.light, buildGhosttyTheme(tokens.variants.light))
    return [PATHS.output.ghostty.dark, PATHS.output.ghostty.light]
  },
  async install() {
    await installFile(PATHS.output.ghostty.dark, PATHS.install.ghostty.dark)
    await installFile(PATHS.output.ghostty.light, PATHS.install.ghostty.light)
    return [PATHS.install.ghostty.dark, PATHS.install.ghostty.light]
  },
}
