import { PATHS } from "../paths"
import type { CreateInstallModule, ThemeTokens, Variant } from "../types"
import { installFile, writeText } from "../utils"

function buildOhMyZshTheme(variant: Variant): string {
  return `# Generated by custom-themes/create/apps/oh-my-zsh.ts
local user_bg="${variant.foregroundMuted}"
local user_fg="${variant.foreground}"
local path_bg="${variant.border}"
local path_fg="${variant.foreground}"
local info_color="${variant.accent}"
local muted_color="${variant.foregroundMuted}"
local prompt_color="${variant.accent}"

function prompt_context_line() {
  print -nr -- "%K{\${user_bg}}%F{\${user_fg}} ⌘ %n %k%f%K{\${path_bg}}%F{\${path_fg}} %~ %k%f"
}

function parse_git_branch() {
  git symbolic-ref --short HEAD 2>/dev/null || git rev-parse --short HEAD 2>/dev/null
}

function prompt_git_line() {
  local folder branch git_line
  local -i ahead behind
  folder="\${PWD:t}"
  branch=$(parse_git_branch)
  git_line="%F{\${info_color}}\${folder}"

  if [[ -n "$branch" ]]; then
    ahead=0
    behind=0
    local counts
    local -a counts_parts
    counts=$(git rev-list --left-right --count @{upstream}...HEAD 2>/dev/null)
    if [[ -n "$counts" ]]; then
      counts_parts=(\${=counts})
      [[ \${counts_parts[1]} == <-> ]] && behind=\${counts_parts[1]}
      [[ \${counts_parts[2]} == <-> ]] && ahead=\${counts_parts[2]}
    fi

    git_line+=" on \${branch}"
    (( ahead > 0 )) && git_line+=" ↑\${ahead}"
    (( behind > 0 )) && git_line+=" ↓\${behind}"
  fi

  git_line+="%f"
  print -nr -- "$git_line"
}

function prompt_input_line() {
  print -nr -- "%F{\${muted_color}}○%f %F{\${prompt_color}}❯%f"
}

PROMPT='$(prompt_context_line)\n$(prompt_git_line)\n$(prompt_input_line) '
`
}

export const ohMyZshApp: CreateInstallModule = {
  appName: "oh-my-zsh",
  async create(tokens: ThemeTokens) {
    const dark = buildOhMyZshTheme(tokens.variants.dark)
    const light = buildOhMyZshTheme(tokens.variants.light)

    await writeText(PATHS.output["oh-my-zsh"].dark, dark)
    await writeText(PATHS.output["oh-my-zsh"].light, light)

    return [PATHS.output["oh-my-zsh"].dark, PATHS.output["oh-my-zsh"].light]
  },
  async install() {
    await installFile(PATHS.output["oh-my-zsh"].dark, PATHS.install["oh-my-zsh"].dark)
    await installFile(PATHS.output["oh-my-zsh"].light, PATHS.install["oh-my-zsh"].light)
    return [PATHS.install["oh-my-zsh"].dark, PATHS.install["oh-my-zsh"].light]
  },
}
